customhost = "employee.cldnotqrt2jn.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "attendance"
custombucket = "choojenjiun-employee"
customregion = "us-east-1"
